### ISSUE TITLE
[bug] github action deploy all failed

### ISSUE THREAD

**Issue by 4923** [4923/vuepress#4]
### reproduce
add - commit - push 할 시 작업 내용이 반영되지 않음을 PWA 설치 과정에서 확인.  
배포 자동화 과정을 중간 테스트 없이 바로 진행했으므로 마크다운 내용들 변경해가면서 테스트할 필요 있음.  
- 이후 PWA 이슈 없는지 확인 할 것
- 이전 #2 이슈 해결되지 않은것과 관계가 있는지 확인 할 것

- [vuepress/Actions](https://github.com/4923/vuepress/actions)
<img width="984" alt="image" src="https://user-images.githubusercontent.com/60145951/160451149-ee18be15-3797-4f87-a0d2-e999b897d65f.png">

**Comment by 4923** [comment]
### 작업내용
- 마크다운 편집 후 `push` : [commit](https://github.com/4923/vuepress/commit/6d89fc8cf05eba642213d2402eac0ede5f6e2e87)
- 해당 html 확인했을 때 제대로 빌드되지 않는데 왜...?
  - jenkey2011에서 빌드까지 진행해주는데 안되는걸 보면 main.yml에서 문제가 생긴걸지도 모르겠다.
  - `No matching page found` ... 이 에러 메시지가 많이 발견됐는데 빌드가 제대로 되지 않았기 때문으로 보임.

<details>
<summary>error log</summary>

```
[vuepress] No matching page found for sidebar item "/cs/intro"
[79](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:79)
[vuepress] No matching page found for sidebar item "/fe/intro"
[80](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:80)
[vuepress] No matching page found for sidebar item "/django/intro"
[81](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:81)
[vuepress] No matching page found for sidebar item "/cs/intro"
[82](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:82)
[vuepress] No matching page found for sidebar item "/fe/intro"
[83](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:83)
[vuepress] No matching page found for sidebar item "/django/intro"
[84](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:84)
[vuepress] No matching page found for sidebar item "/cs/intro"
[85](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:85)
[vuepress] No matching page found for sidebar item "/fe/intro"
[86](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:86)
[vuepress] No matching page found for sidebar item "/django/intro"
[87](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:87)
[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"
[88](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:88)

[89](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:89)
found in
[90](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:90)

[91](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:91)
---> <SidebarLinks>
[92](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:92)
       <DropdownTransition>
[93](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:93)
         <SidebarGroup>
[94](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:94)
           <SidebarLinks>
[95](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:95)
             <Sidebar>
[96](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:96)
               <Layout>
[97](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:97)
                 <GlobalLayout>
[98](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:98)
                   <Root>
[99](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:99)
[vuepress] No matching page found for sidebar item "/cs/intro"
[100](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:100)
[vuepress] No matching page found for sidebar item "/fe/intro"
[151](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:151)
           <SidebarLinks>
[152](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:152)
             <Sidebar>
[153](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:153)
               <Layout>
[154](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:154)
                 <GlobalLayout>
[155](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:155)
                   <Root>
[156](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:156)
[vuepress] No matching page found for sidebar item "/cs/intro"
[157](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:157)
[vuepress] No matching page found for sidebar item "/fe/intro"
[158](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:158)
[vuepress] No matching page found for sidebar item "/django/intro"
[159](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:159)
[vuepress] No matching page found for sidebar item "/cs/intro"
[160](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:160)
[vuepress] No matching page found for sidebar item "/fe/intro"
[161](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:161)
[vuepress] No matching page found for sidebar item "/django/intro"
[162](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:162)
[vuepress] No matching page found for sidebar item "/cs/intro"
[163](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:163)
[vuepress] No matching page found for sidebar item "/fe/intro"
[164](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:164)
[vuepress] No matching page found for sidebar item "/django/intro"
[165](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:165)
[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"
[166](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:166)

[167](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:167)
found in
[168](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:168)

[169](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:169)
---> <SidebarLinks>
[170](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:170)
       <DropdownTransition>
[171](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:171)
         <SidebarGroup>
[172](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:172)
           <SidebarLinks>
[173](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:173)
             <Sidebar>
[174](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:174)
               <Layout>
[175](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:175)
                 <GlobalLayout>
[176](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:176)
                   <Root>
[177](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:177)
error Error rendering /CS/intro.html: false
[178](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:178)
undefined
[179](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:179)
error Error rendering /Django/intro.html: false
[180](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:180)
undefined
[181](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:181)
error Error rendering /FE/intro.html: false
[182](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:182)
undefined
[183](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:183)
error Error rendering /: false
[184](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:184)
undefined
[185](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:185)
error Error rendering /intro.html: false
[186](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:186)
undefined
[187](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:187)
TypeError: Cannot read property 'match' of undefined
[188](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:188)
    at getHash (node_modules/@vuepress/theme-default/util/index.js:13:21)
[189](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:189)
    at isActive (node_modules/@vuepress/theme-default/util/index.js:47:19)
[190](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:190)
    at render (node_modules/@vuepress/theme-default/components/SidebarLink.vue:25:0)
[191](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:191)
    at renderWithStyleInjection (node_modules/vue-loader/lib/runtime/componentNormalizer.js:83:0)
[192](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:192)
    at createFunctionalComponent (/github/workspace/node_modules/vue/dist/vue.runtime.common.dev.js:3071:30)
[193](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:193)
    at createComponent (/github/workspace/node_modules/vue/dist/vue.runtime.common.dev.js:3244:12)
[194](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:194)
    at _createElement (/github/workspace/node_modules/vue/dist/vue.runtime.common.dev.js:3436:15)
[195](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:195)
    at createElement (/github/workspace/node_modules/vue/dist/vue.runtime.common.dev.js:3368:10)
[196](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:196)
    at vm._c (/github/workspace/node_modules/vue/dist/vue.runtime.common.dev.js:3505:42)
[197](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:197)
    at 1.server-bundle.js:1054:492
[198](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:198)
    at Proxy.renderList (/github/workspace/node_modules/vue/dist/vue.runtime.common.dev.js:2640:16)
[199](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:199)
    at Proxy.SidebarLinksvue_type_template_id_1da4684a_render (node_modules/@vuepress/theme-default/components/SidebarLinks.vue?5fd7:1:152)
[200](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:200)
    at VueComponent.Vue._render (/github/workspace/node_modules/vue/dist/vue.runtime.common.dev.js:3559:22)
[201](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:201)
    at resolve (/github/workspace/node_modules/vue-server-renderer/build.dev.js:8444:27)
[202](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:202)
    at waitForServerPrefetch (/github/workspace/node_modules/vue-server-renderer/build.dev.js:8316:3)
[203](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:203)
    at renderComponentInner (/github/workspace/node_modules/vue-server-renderer/build.dev.js:8455:3)
[204](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:204)
error Command failed with exit code 1.
[205](https://github.com/4923/vuepress/runs/5731622781?check_suite_focus=true#step:4:205)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

**Comment by 4923** [comment]
> https://github.com/4923/vuepress/issues/4#issuecomment-1081409408

### try 1
build 문제로 생각돼서 `sh deploy.sh` 로 수동 배포 했을땐 제대로 배포 되었다.
- [정상 배포 log](https://github.com/4923/vuepress/actions/runs/2056551586)
- *그런데? 왜 dist에는 변경된 내용이 html로 뜨지 않는가...*
<img width="500" alt="image" src="https://user-images.githubusercontent.com/60145951/160538647-461267eb-c24d-424c-8a15-e3973b618ba5.png">

### try 2
그럼 자동화 과정에서 문제가 생겼다는 말이니 token쪽을 확인해봐야겠다.  
<img width="400" alt="image" src="https://user-images.githubusercontent.com/60145951/160539321-917b514a-693e-4ee4-b3d0-ea08d281ab9a.png">  
토큰을 확인해보니 never used라고 적혀있어서 regenerate 후 다시 입력해봤다.  
trigger event가 push이므로 실험을 위해 문서를 편집 후 push
- [배포 실패 log](https://github.com/4923/vuepress/settings/secrets/actions)
<img width="500" alt="image" src="https://user-images.githubusercontent.com/60145951/160540414-9204d639-68e4-41d8-b20b-17a36636b8b6.png">

Github Action 문제이니 관련 과정을 살펴봅시다

**Comment by 4923** [comment]
### solution
**가능성 있던 문제**
1. [eb0e91cecccfe5012917790825f25bb4132fa393] 카테고리를 인식하지 못한 문제를 해결하기 위해: `config.json`에서 sidebar에 첫 페이지 `intro.md`를 추가
2. [eb8884b45cc886710be1d1ccf7a6ff5b4dd2d91e] 대소문자 문제: `config.json`에서 sidebar의 children 경로를 dir이름과 통일
    - 생성할 떄 dir 이름을 대문자로 지정했는데 이게 문제가 될 것 같아 중간에 소문자로 수정-통일함. 
    - 변경했는데도 github에는 대문자로 올라와있어 (*문제 확인필요) 다시 대문자로 돌림
3. [eff48ac080beec7e4c9a05bd9930d95e2ebaec0b] `intro.md` 추가시 경로 변경: /intro.md/ 가 아니라 /intro.md 로 변경  

**Github Action 배포 자동화 성공: solution 3**
<img width="500" alt="image" src="https://user-images.githubusercontent.com/60145951/160549604-eee16e23-0923-404c-926f-bc1989ddfa8a.png">

### 결과적으로, 
1. 첫 페이지 역할을 하는 (intro.md) 파일은 `config.json` 에 올라와야하고
2. 경로는 `/page-name.md` 와 같이 좌측에만 `/` slash가 포함되어야하며
3. config.json에서 sidebar/children의 경로는 대소문자를 구분하지 않는다.

**Comment by 4923** [comment]
Github Action이 제대로 작동되니 Personal access token도 사용되었다고 제대로 뜬다.

| before | after |
| :-: | :-: |
| ![before using GA token](https://user-images.githubusercontent.com/60145951/160539321-917b514a-693e-4ee4-b3d0-ea08d281ab9a.png) | ![after using GA token](https://user-images.githubusercontent.com/60145951/160551469-e62c91c0-35c9-4c9d-9315-872ba490be35.png) |

**Comment by 4923** [comment]
test deploy부터 문제없이 돌아가고 있는 상태였다. 
변경 내용이 제대로 반영되지 않는 느낌이 들 땐 `쿠키 삭제` 또는 타 브라우저를 사용해서 접근해 볼 것

| intro page | CS intro page |
| :-: | :-:  |
|![intro](https://user-images.githubusercontent.com/60145951/160556595-597ee323-8367-41bd-9873-96d07f5d52d8.png)| ![CS/intro](https://user-images.githubusercontent.com/60145951/160556696-e811b88e-3d41-4230-8ca5-ea45ad42246c.png) |
