### ISSUE TITLE
[bug] utterances + vuepress Deploying Error

### ISSUE THREAD

**Issue by 4923** [4923/vuepress#6]
### related to
- (작업내용 기록) 14216bcab5b1b0049f8639b911de0e735e1a3f71
- (작업) 4dd6cef75e7235ddaee45fba80c4f6e3cfd08709

## [github action log](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true)

<details>

<summary> log </summary>

```
@ ./docs/.vuepress/theme/Layout.vue?vue&type=script&lang=js& (./node_modules/cache-loader/dist/cjs.js??ref--3-0!./node_modules/babel-loader/lib??ref--3-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./docs/.vuepress/theme/Layout.vue?vue&type=script&lang=js&) 7:0-52 11:18-30
[530](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:530)
 @ ./docs/.vuepress/theme/Layout.vue?vue&type=script&lang=js&
[531](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:531)
 @ ./docs/.vuepress/theme/Layout.vue
[532](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:532)
 @ ./node_modules/@vuepress/core/.temp/internal/layout-components.js
[533](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:533)
 @ ./node_modules/@vuepress/core/lib/client/util.js
[534](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:534)
 @ ./node_modules/@vuepress/core/lib/client/app.js
[535](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:535)
 @ ./node_modules/@vuepress/core/lib/client/serverEntry.js
[536](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:536)
 @ multi ./node_modules/@vuepress/core/lib/client/serverEntry.js
[537](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:537)
Error: Failed to compile with errors.
[538](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:538)
    at /github/workspace/node_modules/@vuepress/core/lib/node/build/index.js:190:16
[539](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:539)
    at finalCallback (/github/workspace/node_modules/webpack/lib/MultiCompiler.js:254:12)
[540](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:540)
    at /github/workspace/node_modules/webpack/lib/MultiCompiler.js:277:6
[541](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:541)
    at done (/github/workspace/node_modules/neo-async/async.js:2931:13)
[542](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:542)
    at runCompilers (/github/workspace/node_modules/webpack/lib/MultiCompiler.js:181:48)
[543](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:543)
    at /github/workspace/node_modules/webpack/lib/MultiCompiler.js:188:7
[544](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:544)
    at /github/workspace/node_modules/webpack/lib/MultiCompiler.js:270:7
[545](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:545)
    at finalCallback (/github/workspace/node_modules/webpack/lib/Compiler.js:257:39)
[546](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:546)
    at /github/workspace/node_modules/webpack/lib/Compiler.js:273:13
[547](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:547)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/github/workspace/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
[548](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:548)
    at AsyncSeriesHook.lazyCompileHook (/github/workspace/node_modules/tapable/lib/Hook.js:154:20)
[549](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:549)
    at onCompiled (/github/workspace/node_modules/webpack/lib/Compiler.js:271:21)
[550](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:550)
    at /github/workspace/node_modules/webpack/lib/Compiler.js:681:15
[551](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:551)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/github/workspace/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
[552](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:552)
    at AsyncSeriesHook.lazyCompileHook (/github/workspace/node_modules/tapable/lib/Hook.js:154:20)
[553](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:553)
    at /github/workspace/node_modules/webpack/lib/Compiler.js:678:31
[554](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:554)
error Command failed with exit code 1.
[555](https://github.com/4923/vuepress/runs/6093942794?check_suite_focus=true#step:4:555)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

- Vuepress post에서 `<script>` 를 사용할 수 없어 `/theme/` 을 만들어 관리하는데, 이 과정에서 vuepress directory 구조에 대한 이해가 부족해 디버깅 불가
- [참고1: 원본코드](https://kyounghwan01.github.io/blog/Vue/vuepress/vuepress-github-comment/)
- [참고2: vuepress에서 theme을 만드는 이유](https://junilhwang.github.io/TIL/Vuepress/Utterances/#repository)

### ToDo's

- [x] 왜 utterances에서 참고 1 코드로 변하게 되었는지 확인 후 기록
- [x] directory 구조를 기본 vuepress project에서 변형했는데 그것이 영향을 미치는 것인지 확인

**Comment by 4923** [comment]
> 관련 commit 9d31ddcfaab5aa819517e847d3301adf6c27d0ca

`Comment.vue` 의 위치가 문제인 것 같아서 theme/ 하위로 이동시켰는데 그게 문제가 아닌 것 같다.

**Comment by 4923** [comment]
### 폴더 구조를 바꿔보자!

<details>
<summary>action log</summary>

```
...

Module not found: Error: Can't resolve '@parent-theme/layouts/Layout.vue' in '/github/workspace/docs/.vuepress/theme'
[410](https://github.com/4923/vuepress/runs/6094611914?check_suite_focus=true#step:4:410)
resolve '@parent-theme/layouts/Layout.vue' in '/github/workspace/docs/.vuepress/theme'

...
```

</details>

action log를 보니 `layout.vue`에서 `import ParentLayout from "@parent-theme/layouts/Layout.vue";` 경로를 불러오는데 현재 내 디렉토리 구조가 아래와 같은 상황이라 layouts을 불러오지 못하는 것 같다.

<img width="207" alt="image" src="https://user-images.githubusercontent.com/60145951/164228323-6d52988e-e9d1-4937-a828-3c9969814907.png">

### 결정사항
- layouts 폴더를 만들거나 경로를 변경하거나 해야하는데 앞으로도 계속 쓰게 될 것이므로 폴더 하나를 새로 만든다.
- components 폴더를 만들고 그 안에 Comment.vue를 이동시킨다.
